### ISSUE TITLE
Command 'pip install mujoco' ; not working

### ISSUE THREAD

**Issue by faizan6557** [NeshOfficial/Deepmine-Tec#8]
Hello, while running out this project , command : pip install mujoco showig th error for 'source pacakges arent available'
kindly if you could sort this. Thank you

**Comment by rehan985** [comment]
Hey Faizan, thank you for your concern. Generally this  error occurs when you are not using all the pre requisites as mentioned in the Readme file.Kinldy go through readme again and carefully. Also do ensure you are using Python (>= 3.8).Let us know if you still face any issue. 
Thanks!
